version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: user_microservice
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password